"""Add chart.image_type

Revision ID: 9e16888e1dee
Revises: 8618836a3c5c
Create Date: 2023-06-13 21:53:15.573008

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9e16888e1dee"
down_revision = "8618836a3c5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chart", sa.Column("image_type", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chart", "image_type")
    # ### end Alembic commands ###
