"""Chart

Revision ID: 868f2f867118
Revises:
Create Date: 2023-05-29 16:51:25.091270

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "868f2f867118"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chart",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("md5_hash", sa.String(), nullable=False),
        sa.Column("storage_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chart")
    # ### end Alembic commands ###
