"""Use pickle

Revision ID: 8618836a3c5c
Revises: 868f2f867118
Create Date: 2023-06-04 11:45:01.650409

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8618836a3c5c"
down_revision = "868f2f867118"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chart", sa.Column("data", sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chart", "data")
    # ### end Alembic commands ###
